import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#cc97ff",
        "primary-fixed": "#c284ff",
        "inverse-primary": "#842cd3",
        surface: "#0d0d17",
        "primary-container": "#c284ff",
        background: "#0d0d17",
        "surface-container-highest": "#242433",
        "on-primary-fixed": "#000000",
        "surface-container-high": "#1e1e2c",
        primary: "#A855F7",
        "on-error-container": "#ffb2b9",
        "on-primary-fixed-variant": "#430076",
        "outline-variant": "#474752",
        "secondary-fixed-dim": "#2be800",
        secondary: "#2ff801",
        "on-primary-container": "#360061",
        "on-background": "#efecfb",
        "surface-bright": "#2b2b3a",
        "on-secondary-fixed": "#064200",
        "on-tertiary-container": "#570018",
        "inverse-surface": "#fcf8ff",
        "primary-fixed-dim": "#b971ff",
        "error-container": "#a70138",
        "on-error": "#490013",
        "surface-container": "#181825",
        "on-tertiary": "#680921",
        "inverse-on-surface": "#555460",
        "surface-variant": "#242433",
        "surface-dim": "#0d0d17",
        "secondary-fixed": "#2ff801",
        "surface-container-low": "#12121d",
        "on-surface": "#efecfb",
        "on-secondary-container": "#e7ffd9",
        tertiary: "#ff95a0",
        "on-surface-variant": "#aca9b7",
        outline: "#757481",
        "tertiary-container": "#fe7e8e",
        "on-secondary-fixed-variant": "#0d6200",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed-variant": "#711227",
        "secondary-container": "#106e00",
        error: "#ff6e84",
        "tertiary-fixed-dim": "#fa7c8b",
        "tertiary-fixed": "#ff909c",
        "on-secondary": "#0b5800",
        "on-tertiary-fixed": "#39000d",
        "secondary-dim": "#2be800",
        "error-dim": "#d73357",
        "primary-dim": "#9c48ea",
        "electric-purple": "#A855F7",
        "neon-green": "#2ff801",
        "black-piano": "#050505",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        "max-content-width": "780px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        body: ["Inter", ...defaultTheme.fontFamily.sans],
        h1: ["Inter", ...defaultTheme.fontFamily.sans],
        h2: ["Inter", ...defaultTheme.fontFamily.sans],
        label: ['"Public Sans"', ...defaultTheme.fontFamily.sans],
        display: ['"Orbitron"', ...defaultTheme.fontFamily.sans],
        code: ['"Public Sans"', "monospace", ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        body: ["1rem", { lineHeight: "1.7", fontWeight: "400" }],
        code: ["0.875rem", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["1.75rem", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        h1: ["2.5rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        label: ["0.75rem", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      maxWidth: {
        content: "780px",
        page: "1280px",
        "page-narrow": "1100px",
      },
    },
  },
  plugins: [],
};
