import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "var(--accent)",
        "primary-fixed": "var(--accent)",
        "inverse-primary": "var(--accent-hover)",
        surface: "var(--bg-primary)",
        "primary-container": "var(--accent-dim)",
        background: "var(--body-bg-color)",
        "surface-container-highest": "var(--border-hover)",
        "on-primary-fixed": "var(--text-primary)",
        "surface-container-high": "var(--bg-elevated)",
        primary: "var(--accent)",
        "on-error-container": "var(--danger)",
        "on-primary-fixed-variant": "var(--accent-hover)",
        "outline-variant": "var(--border-hover)",
        "secondary-fixed-dim": "var(--success)",
        secondary: "var(--success)",
        "on-primary-container": "var(--accent-hover)",
        "on-background": "var(--text-primary)",
        "surface-bright": "var(--bg-elevated)",
        "on-secondary-fixed": "var(--success)",
        "on-tertiary-container": "var(--warning)",
        "inverse-surface": "var(--bg-card)",
        "primary-fixed-dim": "var(--accent-hover)",
        "error-container": "var(--danger)",
        "on-error": "#ffffff",
        "surface-container": "var(--bg-elevated)",
        "on-tertiary": "var(--warning)",
        "inverse-on-surface": "var(--text-primary)",
        "surface-variant": "var(--border-hover)",
        "surface-dim": "var(--bg-primary)",
        "secondary-fixed": "var(--success)",
        "surface-container-low": "var(--bg-card)",
        "on-surface": "var(--text-primary)",
        "on-secondary-container": "var(--success)",
        tertiary: "var(--warning)",
        "on-surface-variant": "var(--text-secondary)",
        outline: "var(--border)",
        "tertiary-container": "var(--warning)",
        "on-secondary-fixed-variant": "var(--success)",
        "on-primary": "#ffffff",
        "surface-container-lowest": "var(--bg-primary)",
        "on-tertiary-fixed-variant": "var(--warning)",
        "secondary-container": "var(--success)",
        error: "var(--danger)",
        "tertiary-fixed-dim": "var(--warning)",
        "tertiary-fixed": "var(--warning)",
        "on-secondary": "var(--success)",
        "on-tertiary-fixed": "var(--warning)",
        "secondary-dim": "var(--success)",
        "error-dim": "var(--danger)",
        "primary-dim": "var(--accent-hover)",
        "electric-purple": "var(--accent)",
        "neon-green": "var(--success)",
        "black-piano": "var(--bg-primary)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        "max-content-width": "960px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        body: ["Inter", ...defaultTheme.fontFamily.sans],
        h1: ["Inter", ...defaultTheme.fontFamily.sans],
        h2: ["Inter", ...defaultTheme.fontFamily.sans],
        label: ['"Public Sans"', ...defaultTheme.fontFamily.sans],
        display: ['"Orbitron"', ...defaultTheme.fontFamily.sans],
        code: ['"Public Sans"', "monospace", ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        body: ["1.125rem", { lineHeight: "1.7", fontWeight: "400" }],
        code: ["0.875rem", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["1.75rem", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        h1: ["2.5rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        label: ["0.75rem", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      maxWidth: {
        content: "780px",
        page: "1440px",
        "page-narrow": "1100px",
      },
    },
  },
  plugins: [],
};
