import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "var(--accent)",
        "primary-fixed": "var(--accent)",
        "inverse-primary": "var(--accent-hover)",
        surface: "var(--bg-primary)",
        "primary-container": "var(--accent)",
        background: "var(--body-bg-color)",
        "surface-container-highest": "var(--border-hover)",
        "on-primary-fixed": "var(--text-primary)",
        "surface-container-high": "var(--bg-elevated)",
        primary: "var(--accent)",
        "on-error-container": "var(--danger)",
        "on-primary-fixed-variant": "var(--accent-hover)",
        "outline-variant": "var(--border)",
        "secondary-fixed-dim": "var(--success)",
        secondary: "var(--success)",
        "on-primary-container": "#ffffff",
        "on-background": "var(--text-primary)",
        "surface-bright": "var(--bg-elevated)",
        "on-secondary-fixed": "var(--success)",
        "on-tertiary-container": "var(--warning)",
        "inverse-surface": "var(--bg-card)",
        "primary-fixed-dim": "var(--accent-hover)",
        "error-container": "var(--danger)",
        "on-error": "#ffffff",
        "surface-container": "var(--bg-card)",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "var(--text-primary)",
        "surface-variant": "var(--border-hover)",
        "surface-dim": "var(--bg-primary)",
        "secondary-fixed": "var(--success)",
        "surface-container-low": "var(--bg-card)",
        "on-surface": "var(--text-primary)",
        "on-secondary-container": "var(--success)",
        tertiary: "var(--warning)",
        "on-surface-variant": "var(--text-secondary)",
        outline: "var(--border-hover)",
        "tertiary-container": "var(--warning)",
        "on-secondary-fixed-variant": "var(--success)",
        "on-primary": "#ffffff",
        "surface-container-lowest": "var(--bg-primary)",
        "on-tertiary-fixed-variant": "var(--warning)",
        "secondary-container": "var(--success)",
        error: "var(--danger)",
        "tertiary-fixed-dim": "var(--warning)",
        "tertiary-fixed": "var(--warning)",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "var(--warning)",
        "secondary-dim": "var(--success)",
        "error-dim": "var(--danger)",
        "primary-dim": "var(--accent-hover)",
        "electric-purple": "var(--accent)",
        "neon-green": "var(--success)",
        "black-piano": "var(--bg-primary)",
        "surface-pure": "var(--bg-secondary)",
        "border-subtle": "var(--border)",
        "border-dim": "var(--border)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-muted)",
        "accent-dim": "var(--accent-dim)",
        "accent-glow": "var(--accent-glow)",
        "success-dim": "var(--success-dim)",
        "warning-dim": "var(--warning-dim)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        xxl: "48px",
        gutter: "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "max-content-width": "960px",
      },
      fontFamily: {
        body: ["Geist", ...defaultTheme.fontFamily.sans],
        h1: ["Geist", ...defaultTheme.fontFamily.sans],
        h2: ["Geist", ...defaultTheme.fontFamily.sans],
        h3: ["Geist", ...defaultTheme.fontFamily.sans],
        h4: ["Geist", ...defaultTheme.fontFamily.sans],
        label: ["Geist", ...defaultTheme.fontFamily.sans],
        display: ["Geist", ...defaultTheme.fontFamily.sans],
        code: ["Geist", "monospace", ...defaultTheme.fontFamily.sans],
        "display-lg": ["Geist", ...defaultTheme.fontFamily.sans],
        "headline-lg": ["Geist", ...defaultTheme.fontFamily.sans],
        "headline-md": ["Geist", ...defaultTheme.fontFamily.sans],
        "body-lg": ["Geist", ...defaultTheme.fontFamily.sans],
        "body-md": ["Geist", ...defaultTheme.fontFamily.sans],
        "label-md": ["Geist", ...defaultTheme.fontFamily.sans],
        "mono-sm": ["Geist", "monospace", ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        body: ["1.125rem", { lineHeight: "1.7", fontWeight: "400" }],
        code: ["0.875rem", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["1.75rem", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        h1: ["2.5rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        label: ["0.75rem", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["3rem", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["2rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["0.875rem", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "mono-sm": ["0.75rem", { lineHeight: "1.4", fontWeight: "400" }],
      },
      maxWidth: {
        content: "780px",
        page: "1200px",
        "page-narrow": "1100px",
      },
    },
  },
  plugins: [],
};
